apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vmanager-webhook-manager
  name: vmanager-webhook-manager
  namespace: vmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vmanager-webhook-manager
  template:
    metadata:
      labels:
        app: vmanager-webhook-manager
    spec:
      serviceAccountName: all-powerful-sa
      containers:
        - name: webhook-manager
          args:
            - -v=5
          image: vacantsh/webhook-manager:1.0
          imagePullPolicy: Never
---
apiVersion: v1
kind: Service
metadata:
  name: vmanager-webhook
  namespace: vmanager
  labels:
    app: vmanager-webhook-manager
spec:
  ports:
    - port: 443
      protocol: TCP
      targetPort: 8443
  selector:
    app: vmanager-webhook-manager
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: all-powerful-sa
  namespace: vmanager
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: all-access-cluster-role
rules:
  - apiGroups: ["*"]
    resources: ["*"]
    verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: all-access-cluster-role-binding
subjects:
  - kind: ServiceAccount
    name: all-powerful-sa
    namespace: vmanager
roleRef:
  kind: ClusterRole
  name: all-access-cluster-role
  apiGroup: rbac.authorization.k8s.io