apiVersion: admissionregistration.k8s.io/v1
kind: MutatingWebhookConfiguration
metadata:
  name: vmanager-mutate-pod
webhooks:
  - name: mutate.pod.vacant.sh
    admissionReviewVersions:
      - v1
    clientConfig:
      service:
        name: vmanager-webhook
        namespace: vmanager
        path: "/mutate-pod"
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lVSG1KODZpaVBQdGMyLzkzR0NRVnpTNmNMa01Bd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERW1NQ1FHQTFVRUF3d2RkbTFoYm1GblpYSXRkMlZpYUc5dmF5NTJiV0Z1WVdkbGNpNXpkbU13SGhjTgpNalF3TnpJMU1UY3hOekU0V2hjTk16UXdOekl6TVRjeE56RTRXakFvTVNZd0pBWURWUVFEREIxMmJXRnVZV2RsCmNpMTNaV0pvYjI5ckxuWnRZVzVoWjJWeUxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBUEFpUnBsU3h4SVlqMThYWmpjVWdwVmFzUmZBWnNLcGhSUStjYm9QOXNYVU9XMGdlNGhyZjJ4RApERVRPbFdVVUcybENGUnpKSHpzMm1RZlpJdjdTSzNmQm93TDR6cXVqWW11ZjFPODNlTVdtSkxHY29nU1dTdFhZCmphc0FHU2thWTduTFBBdy9SMk81cytDRUNvNllMSkR2K29hb3oxN3B2ejl5OVpVZk8yaXB3ZkRvYzhIZWdiSE4Kd284WjViSi90VWpKb25yZTlEbkdlWEg5N2w3WnJWTUFZUFVvdmlpcGpqYk05UHBlNU1ucW1CU1hCemVydlVXdAppNFBwWnViMlUwWDVjYVBNNkFVSXM5b3pBa0REVUMvK0x4Ym1aUDBoMjJMdnhtMm02clNBK3dKZUIrK25GTVlwCkZqWWhYYnBtSjlyZVhDeDlnajRDMW9HY2NLSmVuREVDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkdTMUlnOVgKSjhRdjU3S0FyZE03Uyt6ZDhBMVlNQjhHQTFVZEl3UVlNQmFBRkdTMUlnOVhKOFF2NTdLQXJkTTdTK3pkOEExWQpNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQVpkVHp1UVU4emJxbmk1CjdZYTZZSCtIZ3pSSTdIYVEzUTlrUUJ2c2pScmRBMW40dlpObmFST29MeGlZTkc3QXRzNG9iOGs3TFhJYVZZUnEKVTg5amphZ2drc1hXdkRiWTJVYm5sQVlveG1sbDNMcnVpNjlLK2hES2dkL0ozUmo1VGNITzk5TmFacFk3NHQ4UAoxaTRxTHFld3JJRXpXc0E3ZUJLVHhEN0FxbGtWZ1BRenBhRytCMllQQzI5OGpJY3Vhb2lkOUtpNnIvcGt1WTZ6Cis3YnRFeS9OYlNOa0VwZVcxc291TkVZci9nVG85bnFvbytTRkhGbitsdW54R0Q3WGpnbXVtb3F1bXUwSkJHUDEKZTcyZkdSM3ZoNnc3QmZJMVJCUjZGSmxZOU9KODJKbjBCc1FKYTJIMjVRWkF5SEFWWUtPV3RKQUVpVlRic0JGZwpmU1NsVkY4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    failurePolicy: Fail
    matchPolicy: Equivalent
    rules:
      - operations: ["CREATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    sideEffects: None
    timeoutSeconds: 3
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: vmanager-validate-pod
webhooks:
  - name: validate.pod.vacant.sh
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: vmanager-webhook
        namespace: vmanager
        path: "/validate-pod"
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lVSG1KODZpaVBQdGMyLzkzR0NRVnpTNmNMa01Bd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERW1NQ1FHQTFVRUF3d2RkbTFoYm1GblpYSXRkMlZpYUc5dmF5NTJiV0Z1WVdkbGNpNXpkbU13SGhjTgpNalF3TnpJMU1UY3hOekU0V2hjTk16UXdOekl6TVRjeE56RTRXakFvTVNZd0pBWURWUVFEREIxMmJXRnVZV2RsCmNpMTNaV0pvYjI5ckxuWnRZVzVoWjJWeUxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBUEFpUnBsU3h4SVlqMThYWmpjVWdwVmFzUmZBWnNLcGhSUStjYm9QOXNYVU9XMGdlNGhyZjJ4RApERVRPbFdVVUcybENGUnpKSHpzMm1RZlpJdjdTSzNmQm93TDR6cXVqWW11ZjFPODNlTVdtSkxHY29nU1dTdFhZCmphc0FHU2thWTduTFBBdy9SMk81cytDRUNvNllMSkR2K29hb3oxN3B2ejl5OVpVZk8yaXB3ZkRvYzhIZWdiSE4Kd284WjViSi90VWpKb25yZTlEbkdlWEg5N2w3WnJWTUFZUFVvdmlpcGpqYk05UHBlNU1ucW1CU1hCemVydlVXdAppNFBwWnViMlUwWDVjYVBNNkFVSXM5b3pBa0REVUMvK0x4Ym1aUDBoMjJMdnhtMm02clNBK3dKZUIrK25GTVlwCkZqWWhYYnBtSjlyZVhDeDlnajRDMW9HY2NLSmVuREVDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkdTMUlnOVgKSjhRdjU3S0FyZE03Uyt6ZDhBMVlNQjhHQTFVZEl3UVlNQmFBRkdTMUlnOVhKOFF2NTdLQXJkTTdTK3pkOEExWQpNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQVpkVHp1UVU4emJxbmk1CjdZYTZZSCtIZ3pSSTdIYVEzUTlrUUJ2c2pScmRBMW40dlpObmFST29MeGlZTkc3QXRzNG9iOGs3TFhJYVZZUnEKVTg5amphZ2drc1hXdkRiWTJVYm5sQVlveG1sbDNMcnVpNjlLK2hES2dkL0ozUmo1VGNITzk5TmFacFk3NHQ4UAoxaTRxTHFld3JJRXpXc0E3ZUJLVHhEN0FxbGtWZ1BRenBhRytCMllQQzI5OGpJY3Vhb2lkOUtpNnIvcGt1WTZ6Cis3YnRFeS9OYlNOa0VwZVcxc291TkVZci9nVG85bnFvbytTRkhGbitsdW54R0Q3WGpnbXVtb3F1bXUwSkJHUDEKZTcyZkdSM3ZoNnc3QmZJMVJCUjZGSmxZOU9KODJKbjBCc1FKYTJIMjVRWkF5SEFWWUtPV3RKQUVpVlRic0JGZwpmU1NsVkY4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: ["UPDATE"]
        apiGroups: [""]
        apiVersions: ["v1"]
        resources: ["pods"]
        scope: "Namespaced"
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 3
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: vmanager-validate-deployment
webhooks:
  - name: validate.deployment.vacant.sh
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: vmanager-webhook
        namespace: vmanager
        path: "/validate-deployment"
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lVSG1KODZpaVBQdGMyLzkzR0NRVnpTNmNMa01Bd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERW1NQ1FHQTFVRUF3d2RkbTFoYm1GblpYSXRkMlZpYUc5dmF5NTJiV0Z1WVdkbGNpNXpkbU13SGhjTgpNalF3TnpJMU1UY3hOekU0V2hjTk16UXdOekl6TVRjeE56RTRXakFvTVNZd0pBWURWUVFEREIxMmJXRnVZV2RsCmNpMTNaV0pvYjI5ckxuWnRZVzVoWjJWeUxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBUEFpUnBsU3h4SVlqMThYWmpjVWdwVmFzUmZBWnNLcGhSUStjYm9QOXNYVU9XMGdlNGhyZjJ4RApERVRPbFdVVUcybENGUnpKSHpzMm1RZlpJdjdTSzNmQm93TDR6cXVqWW11ZjFPODNlTVdtSkxHY29nU1dTdFhZCmphc0FHU2thWTduTFBBdy9SMk81cytDRUNvNllMSkR2K29hb3oxN3B2ejl5OVpVZk8yaXB3ZkRvYzhIZWdiSE4Kd284WjViSi90VWpKb25yZTlEbkdlWEg5N2w3WnJWTUFZUFVvdmlpcGpqYk05UHBlNU1ucW1CU1hCemVydlVXdAppNFBwWnViMlUwWDVjYVBNNkFVSXM5b3pBa0REVUMvK0x4Ym1aUDBoMjJMdnhtMm02clNBK3dKZUIrK25GTVlwCkZqWWhYYnBtSjlyZVhDeDlnajRDMW9HY2NLSmVuREVDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkdTMUlnOVgKSjhRdjU3S0FyZE03Uyt6ZDhBMVlNQjhHQTFVZEl3UVlNQmFBRkdTMUlnOVhKOFF2NTdLQXJkTTdTK3pkOEExWQpNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQVpkVHp1UVU4emJxbmk1CjdZYTZZSCtIZ3pSSTdIYVEzUTlrUUJ2c2pScmRBMW40dlpObmFST29MeGlZTkc3QXRzNG9iOGs3TFhJYVZZUnEKVTg5amphZ2drc1hXdkRiWTJVYm5sQVlveG1sbDNMcnVpNjlLK2hES2dkL0ozUmo1VGNITzk5TmFacFk3NHQ4UAoxaTRxTHFld3JJRXpXc0E3ZUJLVHhEN0FxbGtWZ1BRenBhRytCMllQQzI5OGpJY3Vhb2lkOUtpNnIvcGt1WTZ6Cis3YnRFeS9OYlNOa0VwZVcxc291TkVZci9nVG85bnFvbytTRkhGbitsdW54R0Q3WGpnbXVtb3F1bXUwSkJHUDEKZTcyZkdSM3ZoNnc3QmZJMVJCUjZGSmxZOU9KODJKbjBCc1FKYTJIMjVRWkF5SEFWWUtPV3RKQUVpVlRic0JGZwpmU1NsVkY4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["deployments"]
        scope: "Namespaced"
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 3
---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: vmanager-validate-statefulset
webhooks:
  - name: validate.statefulset.vacant.sh
    admissionReviewVersions: ["v1"]
    clientConfig:
      service:
        name: vmanager-webhook
        namespace: vmanager
        path: "/validate-statefulset"
        port: 443
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSURNVENDQWhtZ0F3SUJBZ0lVSG1KODZpaVBQdGMyLzkzR0NRVnpTNmNMa01Bd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0tERW1NQ1FHQTFVRUF3d2RkbTFoYm1GblpYSXRkMlZpYUc5dmF5NTJiV0Z1WVdkbGNpNXpkbU13SGhjTgpNalF3TnpJMU1UY3hOekU0V2hjTk16UXdOekl6TVRjeE56RTRXakFvTVNZd0pBWURWUVFEREIxMmJXRnVZV2RsCmNpMTNaV0pvYjI5ckxuWnRZVzVoWjJWeUxuTjJZekNDQVNJd0RRWUpLb1pJaHZjTkFRRUJCUUFEZ2dFUEFEQ0MKQVFvQ2dnRUJBUEFpUnBsU3h4SVlqMThYWmpjVWdwVmFzUmZBWnNLcGhSUStjYm9QOXNYVU9XMGdlNGhyZjJ4RApERVRPbFdVVUcybENGUnpKSHpzMm1RZlpJdjdTSzNmQm93TDR6cXVqWW11ZjFPODNlTVdtSkxHY29nU1dTdFhZCmphc0FHU2thWTduTFBBdy9SMk81cytDRUNvNllMSkR2K29hb3oxN3B2ejl5OVpVZk8yaXB3ZkRvYzhIZWdiSE4Kd284WjViSi90VWpKb25yZTlEbkdlWEg5N2w3WnJWTUFZUFVvdmlpcGpqYk05UHBlNU1ucW1CU1hCemVydlVXdAppNFBwWnViMlUwWDVjYVBNNkFVSXM5b3pBa0REVUMvK0x4Ym1aUDBoMjJMdnhtMm02clNBK3dKZUIrK25GTVlwCkZqWWhYYnBtSjlyZVhDeDlnajRDMW9HY2NLSmVuREVDQXdFQUFhTlRNRkV3SFFZRFZSME9CQllFRkdTMUlnOVgKSjhRdjU3S0FyZE03Uyt6ZDhBMVlNQjhHQTFVZEl3UVlNQmFBRkdTMUlnOVhKOFF2NTdLQXJkTTdTK3pkOEExWQpNQThHQTFVZEV3RUIvd1FGTUFNQkFmOHdEUVlKS29aSWh2Y05BUUVMQlFBRGdnRUJBQVpkVHp1UVU4emJxbmk1CjdZYTZZSCtIZ3pSSTdIYVEzUTlrUUJ2c2pScmRBMW40dlpObmFST29MeGlZTkc3QXRzNG9iOGs3TFhJYVZZUnEKVTg5amphZ2drc1hXdkRiWTJVYm5sQVlveG1sbDNMcnVpNjlLK2hES2dkL0ozUmo1VGNITzk5TmFacFk3NHQ4UAoxaTRxTHFld3JJRXpXc0E3ZUJLVHhEN0FxbGtWZ1BRenBhRytCMllQQzI5OGpJY3Vhb2lkOUtpNnIvcGt1WTZ6Cis3YnRFeS9OYlNOa0VwZVcxc291TkVZci9nVG85bnFvbytTRkhGbitsdW54R0Q3WGpnbXVtb3F1bXUwSkJHUDEKZTcyZkdSM3ZoNnc3QmZJMVJCUjZGSmxZOU9KODJKbjBCc1FKYTJIMjVRWkF5SEFWWUtPV3RKQUVpVlRic0JGZwpmU1NsVkY4PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
    rules:
      - operations: ["CREATE", "UPDATE"]
        apiGroups: ["apps"]
        apiVersions: ["v1"]
        resources: ["statefulsets"]
        scope: "Namespaced"
    failurePolicy: Fail
    sideEffects: None
    timeoutSeconds: 3
