apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment1
  labels:
    vacant.sh/optimize-scheduling: "true"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment1
  template:
    metadata:
      labels:
        app: deployment1
    spec:
      containers:
        - name: nginx
          image: nginx:latest
