apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment3
  labels:
    vacant.sh/optimize-scheduling: "true"
    vacant.sh/optimize-scheduling-strategy: "custom"
    vacant.sh/optimize-scheduling-strategy-custom-on-demand: "1"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment3
  template:
    metadata:
      labels:
        app: deployment3
    spec:
      containers:
        - name: nginx
          image: nginx:latest
