apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment2
  labels:
    vacant.sh/optimize-scheduling: "true"
    vacant.sh/optimize-scheduling-strategy: "majority-in-on-demand"
spec:
  replicas: 3
  selector:
    matchLabels:
      app: deployment2
  template:
    metadata:
      labels:
        app: deployment2
    spec:
      containers:
        - name: nginx
          image: nginx:latest
