apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: statefulset1
  labels:
    vacant.sh/optimize-scheduling: "true"
spec:
  serviceName: nginx-service
  replicas: 3
  selector:
    matchLabels:
      app: statefulset1
  template:
    metadata:
      labels:
        app: statefulset1
    spec:
      containers:
        - name: nginx
          image: nginx:latest
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-service
spec:
  ports:
    - port: 80
      name: web
  clusterIP: None
  selector:
    app: nginx
